chore: revert shell, update outdated deps script

diff --git a/.github/actions/deps-outdated/action.yml b/.github/actions/deps-outdated/action.yml
--- a/.github/actions/deps-outdated/action.yml
+++ b/.github/actions/deps-outdated/action.yml
@@ -4,27 +4,27 @@ description: Check for outdated dependencies
 runs:
   using: "composite"
   steps:
-    - name: Install npm-check-updates
-      run: npm i -g npm-check-updates
-      shell: bash
-
     - name: Check for outdated dependencies
       run: |
-        OUTDATED_DEPS=$(ncu)
+        OUTDATED_DEPS_JSON=$(npx ncu --json || true)
 
-        if [ -z "$OUTDATED_DEPS" ]; then
+        if [ -z "$OUTDATED_DEPS_JSON" ] || [ "$OUTDATED_DEPS_JSON" == "{}" ]; then
           echo "No outdated dependencies found."
+          echo "count=0" >> $GITHUB_OUTPUT
         else
-          # Count the number of occurrences of the "→" symbol
-          OUTDATED_COUNT=$(echo "$OUTDATED_DEPS" | grep -o '→' | wc -l)
+          OUTDATED_COUNT=$(echo "$OUTDATED_DEPS_JSON" | jq 'keys | length')
 
-          echo "Outdated dependencies found:"
-          echo "$OUTDATED_DEPS"
-          echo "Total:"
-          echo "$OUTDATED_COUNT"
+          echo "Outdated dependencies found (JSON format):"
+          echo "$OUTDATED_DEPS_JSON"
+          echo "Total outdated: $OUTDATED_COUNT"
+          echo "count=$OUTDATED_COUNT" >> $GITHUB_OUTPUT
 
-          if [ "$OUTDATED_COUNT" -ge 10 ]; then
-            echo "Error: There are $OUTDATED_COUNT outdated dependencies, which is too many. Raise a separate PR to fix it."
+          THRESHOLD=10
+          if [ "$OUTDATED_COUNT" -ge "$THRESHOLD" ]; then
+            echo "::error::There are $OUTDATED_COUNT outdated dependencies (Threshold: $THRESHOLD), which is too many. Please update dependencies in a separate PR."
             exit 1
+          else
+             echo "Number of outdated dependencies ($OUTDATED_COUNT) is below threshold ($THRESHOLD)."
           fi
         fi
+      shell: bash
